---
# tasks file for ansible-role-cloudforms-get-vmname

- name: "Getting Virtual Machine Info"
  uri:
    url: https://{{ rhcf_host }}/api/services/{{ service_id }}?expand=resources&attributes=vms
    method: GET
    user: "{{ rhcf_username }}"
    password: "{{ rhcf_password }}"
    return_content: yes
    validate_certs: False
    headers:
      Content-Type: "application/json"
    status_code: 200, 201
  register: vm_info

- name: "Task Result: Getting Virtual Machine Info"
  debug: var=vm_info

- name: "Setting Virtual Machine Name For Workflow"
  set_stats: 
    data: 
      vm_name: "{{ item.name }}"
  with_items: "{{ vm_info.json.vms }}"
  when: vm_info.json.vms|length == "1"

- name: "Setting Virtual Machine Name For Role"
  set_fact:
    vm_name: "{{ item.name }}"
  with_items: "{{ vm_info.json.vms }}"
  when: vm_info.json.vms|length == "1"

- name: "Fact Result: Setting Virtual Machine Name For Playbook"
  debug: var=vm_name
  when: vm_info.json.vms|length == "1"

- name: "Setting Service Virtual Machines For Workflow"
  set_stats: 
    data: 
      service_vms: "{{ vm_info.json.vms }}"
  when: vm_info.json.vms|length > 1

- name: "Setting Service Virtual Machine For Playbook"
  set_fact:
    service_vms: "{{ vm_info.json.vms }}"
  when: vm_info.json.vms|length > 1

- name: "Fact Result: Setting Service Virtual Machine For Playbook"
  debug: var=service_vms
  when: vm_info.json.vms|length > 1
